http://localhost:4000/
###
http://localhost:4000/blocks
###
POST http://localhost:4000/blocks

{
	"message": "mine!"
}
###
http://localhost:4000/blocks/5193c38a17c8ea39b26f6f554dadabf4a01cc9a453cb931ca5754d224152644f
###
http://localhost:4000/status
###
http://localhost:4000/balance/5b9ef3fc1050b3799a84430c90a201a38647ae434f010e65e5b437f88b0b2c81c3fc2e578f17218b9110940a2f419dfa133a3a5271b5c8353a94e44d91d375d2
###
http://localhost:4000/balance/hoon?total=true
###
http://localhost:4000/balance/eunbee
###
http://localhost:4000/balance/eunbee?total=true
###
POST http://localhost:4000/transactions

{
	"to": "eunbee",
	"amount": 50
}
###
http://localhost:4000/mempool
###
http://localhost:4000/wallet
###
POST http://localhost:4000/peers

{
	"address": "127.0.0.1",
	"port": "3000"
}
###
http://localhost:4000/peers
###
http://localhost:3000/peers